import { TableProps } from "../types";

export default function TableCard({ property }: TableProps) {
  const { head1, head2, head3, head4, row1, row2, row3, row4, row5 } = property;
  return (
    <table>
      <thead>
        <tr className="thead">
          <th>{head1}</th>
          <th>{head2}</th>
          <th>{head3}</th>
          <th>{head4}</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
        <tr>
          <td>{row1}</td>
          <td>{row2}</td>
          <td>{row3}</td>
          <td>{row4}</td>
          <td>{row5}</td>
        </tr>
      </tbody>
    </table>
  );
}
